/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bjTu02sCQjP
 */

function HeroSection() {
  return (
    <section className="w-full py-6 md:py-12 xl:py-16">
      <div className="container grid gap-6 px-4 md:px-6">
        <div className="flex flex-col gap-2 text-center">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-6xl/none">
            Hotel, Car & Experiences
          </h1>
          <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
            Embark on a journey filled with unforgettable experiences. With Chisfis, you can easily book accommodations,
            resort villas, and hotels.
          </p>
        </div>
        <div className="flex items-center justify-center space-x-4">
          <div className="w-full max-w-[400px] rounded-lg">
            <div className="grid w-full grid-cols-3 rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950">
              <select className="h-14 p-4 text-sm bg-transparent border-0 border-r w-full focus:outline-none dark:text-gray-50">
                <option>Stays</option>
                <option>Experiences</option>
                <option>Cars</option>
                <option>Flights</option>
              </select>
              <input
                className="h-14 p-4 text-sm placeholder-gray-500 bg-transparent w-full focus:outline-none dark:placeholder-gray-400 dark:gray-50"
                placeholder="City or place"
                type="text"
              />
              <input
                className="h-14 p-4 text-sm placeholder-gray-500 bg-transparent border-l w-full focus:outline-none dark:placeholder-gray-400 dark:gray-50"
                placeholder="Check-in"
                type="text"
              />
              <input
                className="h-14 p-4 text-sm placeholder-gray-500 bg-transparent border-l w-full focus:outline-none dark:placeholder-gray-400 dark:gray-50"
                placeholder="Check-out"
                type="text"
              />
              <button className="h-14 flex items-center justify-center w-full rounded-r-md bg-gray-900 text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300">
                <SearchIcon className="w-5 h-5 scale-125" />
                <span className="sr-only">Search</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}

export default HeroSection