/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XlLrWDlX7xZ
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"

function NavBar() {
  return (
    <header className="bg-white py-4 shadow-sm">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-4">
        <div className="flex items-center space-x-8">
          <CompassIcon className="h-8 w-8 text-blue-600" />
          <h1 className="text-xl font-semibold text-gray-800">.fis</h1>
          <nav className="hidden space-x-8 lg:flex">
            <Link className="text-sm font-medium text-gray-700 hover:text-gray-900" href="#">
              Travelers
            </Link>
            <div className="relative">
              <button className="flex items-center text-sm font-medium text-gray-700 hover:text-gray-900">
                Templates
                <ChevronDownIcon className="ml-1 h-4 w-4" />
              </button>
            </div>
          </nav>
        </div>
        <div className="flex items-center space-x-4">
          <SearchIcon className="h-6 w-6 text-gray-600" />
          <LayoutGridIcon className="h-6 w-6 text-gray-600" />
          <Button className="rounded-full bg-blue-600 px-4 py-2 text-sm font-medium text-white">
            List your property
          </Button>
          <Avatar>
            <AvatarImage alt="User profile" src="/placeholder.svg?height=32&width=32" />
          </Avatar>
        </div>
      </div>
    </header>
  )
}


function CompassIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function LayoutGridIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>
  )
}


export default NavBar